### ISSUE TITLE
Battle Axe Ice and Fire & Tansheron's Bow +4 are Only Usable by Druid?

### ISSUE THREAD

**Issue by basicals** [SpellholdStudios/Rolles#5]
is this correct?

Both items have an effect Usable by Druid which restricts them to this class.

Druids shouldn't be able to use either axes or bows.

Thank you,

**Comment by GwendolyneFreddy** [comment]
Which version of the mod are you playing because I thought it has been fixed?

**Comment by basicals** [comment]
weidu.log says

~ROLLES/ROLLES.TP2~ #1 #0 // Rolles Safyer: v5.0.4

**Comment by GwendolyneFreddy** [comment]
OK. Sorry, it is my fault: the function was fixed locally, and I forgot to update it at GitHub. I will upload a new package after testing it on a new patch 2.6.6.

**Comment by GwendolyneFreddy** [comment]
Fixed in new version (5.0.5)
